FROM rocker/verse:4.1
RUN Rscript --no-restore --no-save -e "install.packages('ggplot2')"
RUN Rscript --no-restore --no-save -e "install.packages('dplyr')"
RUN Rscript --no-restore --no-save -e "install.packages('RColorBrewer')"
RUN Rscript --no-restore --no-save -e "install.packages('randomForest')"
RUN Rscript --no-restore --no-save -e "install.packages('ROCit')"
RUN Rscript --no-restore --no-save -e "install.packages('shiny')"
RUN Rscript --no-restore --no-save -e "install.packages('ggpubr')"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"wrapfig\",\"ec\",\"ulem\",\"amsmath\",\"capt-of\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"hyperref\",\"iftex\",\"pdftexcmds\",\"infwarerr\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"kvoptions\",\"epstopdf\",\"epstopdf-pkg\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"hanging\",\"grfext\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"etoolbox\",\"xcolor\",\"geometry\"))"
